[workspace]
members = ["slimbus"]

[package]
name = "examples"
edition = "2021"

[dev-dependencies]
slimbus = { path = "./slimbus" }
calloop = "0.12"

serde = { version = "1", features = ["derive"] }
rand = "0.9"
zvariant = { version = "5.4.0", default-features = false }
